version: '3'

services:
   web:
       build:
       container_name: uas_django_blog
       # command: python manage.py runserver 0.0.0.0:9007
       command : gunicorn mysite.wsgi:application --bind 0.0.0.0:9001

       volumes:
          - .:/app
       ports:
          - "9001:9001"