# Generated by Django 3.2.8 on 2022-01-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_artikel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artikel/thumbnail/'),
        ),
    ]
